

services:
  web:
    build: .
    container_name: travel_wishlist_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # Hot reload in dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    networks:
      - travel_net

  db:
    image: postgres:14
    container_name: travel_wishlist_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - travel_net

networks:
  travel_net:

volumes:
  pg_data:
