

services:
  db:
    image: postgres:14
    container_name: travel_wishlist_db
    env_file:
    - .env
    ports:
      - "5432:5432"  # This exposes port 5432 to your local network
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - travel_net

networks:
  travel_net:

volumes:
  pg_data:

