"""debug alembic visibility

Revision ID: 60c2753e7a22
Revises: 68f20974f419
Create Date: 2025-05-27 12:14:44.708544

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "60c2753e7a22"
down_revision: Union[str, None] = "68f20974f419"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
