"""create users table for real this time for real for real

Revision ID: 7f9011f3c6e9
Revises: 0f5b5bcde0a7
Create Date: 2025-05-27 12:27:57.696626

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7f9011f3c6e9"
down_revision: Union[str, None] = "0f5b5bcde0a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
