"""finally found the damn tables

Revision ID: 99899302fc30
Revises: d93356d65520
Create Date: 2025-05-27 12:45:43.243655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99899302fc30"
down_revision: Union[str, None] = "d93356d65520"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wishlist_location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=120), nullable=False),
        sa.Column(
            "added_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("visited", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "visited_location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wishlist_id", sa.Integer(), nullable=False),
        sa.Column("visited_on", sa.DateTime(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wishlist_id"],
            ["wishlist_location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visited_location")
    op.drop_table("wishlist_location")
    # ### end Alembic commands ###
