"""joined visited/wishlist schema

Revision ID: effdd4549725
Revises: f97f6a2f727f
Create Date: 2025-05-28 15:01:52.036927

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "effdd4549725"
down_revision: Union[str, None] = "f97f6a2f727f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
