"""Add latitude and longitude to wishlist_location

Revision ID: f97f6a2f727f
Revises: fe9eb3c597df
Create Date: 2025-05-28 14:37:51.142779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f97f6a2f727f"
down_revision: Union[str, None] = "fe9eb3c597df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wishlist_location", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column(
        "wishlist_location", sa.Column("longitude", sa.Float(), nullable=True)
    )
    op.alter_column(
        "wishlist_location", "city", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "wishlist_location", "country", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wishlist_location", "country", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "wishlist_location", "city", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("wishlist_location", "longitude")
    op.drop_column("wishlist_location", "latitude")
    # ### end Alembic commands ###
