"""create user table for real real no cap

Revision ID: fc6c12504272
Revises: 7f9011f3c6e9
Create Date: 2025-05-27 12:36:24.379783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fc6c12504272"
down_revision: Union[str, None] = "7f9011f3c6e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("role", sa.Enum("ADMIN", "USER", name="userrole"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)

    # These tables likely don’t exist on Railway, so let’s comment them out
    # op.drop_table("visited_location")
    # op.drop_table("wishlist_location")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wishlist_location",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('wishlist_location_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=120), autoincrement=False, nullable=False
        ),
        sa.Column(
            "added_on",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("visited", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="wishlist_location_pkey"),
    )
    op.create_table(
        "visited_location",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("wishlist_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "visited_on", sa.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("rating", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["wishlist_id"],
            ["wishlist_location.id"],
            name="visited_location_wishlist_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="visited_location_pkey"),
    )
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
