"""Add owner_id to visited_location

Revision ID: fe8b8b1ce8b2
Revises: 99899302fc30
Create Date: 2025-05-27 18:43:08.006311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8b8b1ce8b2'
down_revision: Union[str, None] = '99899302fc30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visited_location', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'visited_location', 'users', ['owner_id'], ['id'])
    op.add_column('wishlist_location', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wishlist_location', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist_location', type_='foreignkey')
    op.drop_column('wishlist_location', 'owner_id')
    op.drop_constraint(None, 'visited_location', type_='foreignkey')
    op.drop_column('visited_location', 'owner_id')
    # ### end Alembic commands ###
