"""Add user/location relationships and visited_locations

Revision ID: fe9eb3c597df
Revises: fe8b8b1ce8b2
Create Date: 2025-05-28 12:09:39.270772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe9eb3c597df"
down_revision: Union[str, None] = "fe8b8b1ce8b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wishlist_location", sa.Column("city", sa.String(), nullable=True))
    op.add_column("wishlist_location", sa.Column("country", sa.String(), nullable=True))
    op.alter_column(
        "wishlist_location",
        "description",
        existing_type=sa.VARCHAR(length=120),
        nullable=True,
    )
    op.create_index(
        op.f("ix_wishlist_location_id"), "wishlist_location", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wishlist_location_id"), table_name="wishlist_location")
    op.alter_column(
        "wishlist_location",
        "description",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
    )
    op.drop_column("wishlist_location", "country")
    op.drop_column("wishlist_location", "city")
    # ### end Alembic commands ###
